import { JOB_TYPES_ENUM, JobInterface, WORK_PLACE_TYPE_ENUM } from '@/types/config'

export const JOB_POST_MOCKUP: JobInterface[] = [
    {
        company: 'Meta',
        title: 'UI/UX Engineer',
        summary: 'Design and iterate intuitive digital products that delight our users.',
        description: 'Design and iterate intuitive digital products that delight our users.',
        department: 'Design',
        jobType: JOB_TYPES_ENUM.fulltime,
        location: 'Pasay City, Philippines',
        workLocationType: WORK_PLACE_TYPE_ENUM.onsite,
        activeUntil: '2025-02-08',
    },
    {
        company: 'Plaid',
        title: 'Cybersecurity',
        summary:
            'Responsible for monitoring and protecting networks and systems from cyber threats, implementing security measures, and responding to incidents.',
        description: 'Design and iterate intuitive digital products that delight our users.',
        department: 'Security',
        location: 'Pasay City, Philippines',
        jobType: JOB_TYPES_ENUM.intern,
        workLocationType: WORK_PLACE_TYPE_ENUM.hybrid,
        activeUntil: '2025-02-08',
    },
    {
        company: 'Boat',
        title: 'Full Stack Developer',
        summary: 'Design, develop and implement security solutions and tools to protect our systems and applications.',
        description: 'Design and iterate intuitive digital products that delight our users.',
        department: 'Design',
        location: 'Pasay City, Philippines',
        jobType: JOB_TYPES_ENUM.fulltime,
        workLocationType: WORK_PLACE_TYPE_ENUM.onsite,
        activeUntil: '2025-02-08',
    },
    {
        company: 'BCM',
        title: 'UI/UX Designer',
        summary: 'Design and iterate intuitive digital products that delight our users.',
        description: '',
        department: 'Design',
        jobType: JOB_TYPES_ENUM.fulltime,
        location: 'Pasay City, Philippines',
        workLocationType: WORK_PLACE_TYPE_ENUM.onsite,
        activeUntil: '2025-02-08',
    },
    {
        company: 'CP Company',
        title: 'Cybersecurity intern',
        summary:
            'Responsible for monitoring and protecting networks and systems from cyber threats, implementing security measures, and responding to incidents.',
        description: '',
        department: 'Security',
        jobType: JOB_TYPES_ENUM.intern,
        location: 'Pasay City, Philippines',
        workLocationType: WORK_PLACE_TYPE_ENUM.hybrid,
        activeUntil: '2025-02-08',
    },
    {
        company: 'Boat',
        title: 'Data Engineer',
        summary: 'Design, develop and implement security solutions and tools to protect our systems and applications.',
        description: '',
        department: 'Design',
        jobType: JOB_TYPES_ENUM.fulltime,
        location: 'Pasay City, Philippines',
        workLocationType: WORK_PLACE_TYPE_ENUM.onsite,
        activeUntil: '2024-02-08',
    },
]
